// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for the AllocateQuota method.
public struct AllocateQuotaResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The same operation_id value used in the AllocateQuotaRequest. Used for
  /// logging and diagnostics purposes.
  public var operationId: Swift.String = Swift.String()

  /// Indicates the decision of the allocate.
  public var allocateErrors: [QuotaError] = []

  /// Quota metrics to indicate the result of allocation. Depending on the
  /// request, one or more of the following metrics will be included:
  ///
  /// 1. Per quota group or per quota metric incremental usage will be specified
  /// using the following delta metric :
  ///   "serviceruntime.googleapis.com/api/consumer/quota_used_count"
  ///
  /// 2. The quota limit reached condition will be specified using the following
  /// boolean metric :
  ///   "serviceruntime.googleapis.com/quota/exceeded"
  public var quotaMetrics: [MetricValueSet] = []

  /// ID of the actual config used to process the request.
  public var serviceConfigId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AllocateQuotaResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllocateQuotaResponse().with { $0.operationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let operationId = CodingKeys(stringValue: "operationId")
    static let allocateErrors = CodingKeys(stringValue: "allocateErrors")
    static let quotaMetrics = CodingKeys(stringValue: "quotaMetrics")
    static let serviceConfigId = CodingKeys(stringValue: "serviceConfigId")

    static let _knownKeys: Set<Swift.String> = [
      "operationId",
      "allocateErrors",
      "quotaMetrics",
      "serviceConfigId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationId) {
      self.operationId = value
    }
    if let value = try container.decodeIfPresent([QuotaError].self, forKey: .allocateErrors) {
      self.allocateErrors = value
    }
    if let value = try container.decodeIfPresent([MetricValueSet].self, forKey: .quotaMetrics) {
      self.quotaMetrics = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceConfigId) {
      self.serviceConfigId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.operationId, forKey: .operationId)
    try container.encode(self.allocateErrors, forKey: .allocateErrors)
    try container.encode(self.quotaMetrics, forKey: .quotaMetrics)
    try container.encode(self.serviceConfigId, forKey: .serviceConfigId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.AllocateQuotaResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
