// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for the Check method.
public struct CheckResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The same operation_id value used in the
  /// [CheckRequest][google.api.servicecontrol.v1.CheckRequest]. Used for logging
  /// and diagnostics purposes.
  ///
  /// [google.api.servicecontrol.v1.CheckRequest]: <doc:CheckRequest>
  public var operationId: Swift.String = Swift.String()

  /// Indicate the decision of the check.
  ///
  /// If no check errors are present, the service should process the operation.
  /// Otherwise the service should use the list of errors to determine the
  /// appropriate action.
  public var checkErrors: [CheckError] = []

  /// The actual config id used to process the request.
  public var serviceConfigId: Swift.String = Swift.String()

  /// The current service rollout id used to process the request.
  public var serviceRolloutId: Swift.String = Swift.String()

  /// Feedback data returned from the server during processing a Check request.
  public var checkInfo: CheckResponse.CheckInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CheckResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckResponse().with { $0.operationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let operationId = CodingKeys(stringValue: "operationId")
    static let checkErrors = CodingKeys(stringValue: "checkErrors")
    static let serviceConfigId = CodingKeys(stringValue: "serviceConfigId")
    static let serviceRolloutId = CodingKeys(stringValue: "serviceRolloutId")
    static let checkInfo = CodingKeys(stringValue: "checkInfo")

    static let _knownKeys: Set<Swift.String> = [
      "operationId",
      "checkErrors",
      "serviceConfigId",
      "serviceRolloutId",
      "checkInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationId) {
      self.operationId = value
    }
    if let value = try container.decodeIfPresent([CheckError].self, forKey: .checkErrors) {
      self.checkErrors = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceConfigId) {
      self.serviceConfigId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceRolloutId) {
      self.serviceRolloutId = value
    }
    self.checkInfo = try container.decodeIfPresent(CheckResponse.CheckInfo.self, forKey: .checkInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.operationId, forKey: .operationId)
    try container.encode(self.checkErrors, forKey: .checkErrors)
    try container.encode(self.serviceConfigId, forKey: .serviceConfigId)
    try container.encode(self.serviceRolloutId, forKey: .serviceRolloutId)
    try container.encodeIfPresent(self.checkInfo, forKey: .checkInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Contains additional information about the check operation.
  public struct CheckInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A list of fields and label keys that are ignored by the server.
    /// The client doesn't need to send them for following requests to improve
    /// performance and allow better aggregation.
    public var unusedArguments: [Swift.String] = []

    /// Consumer info of this check.
    public var consumerInfo: CheckResponse.ConsumerInfo? = nil

    /// The unique id of the api key in the format of "apikey:<UID>".
    /// This field will be populated when the consumer passed to Service Control
    /// is an API key and all the API key related validations are successful.
    public var apiKeyUid: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CheckInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CheckInfo().with { $0.unusedArguments = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let unusedArguments = CodingKeys(stringValue: "unusedArguments")
      static let consumerInfo = CodingKeys(stringValue: "consumerInfo")
      static let apiKeyUid = CodingKeys(stringValue: "apiKeyUid")

      static let _knownKeys: Set<Swift.String> = [
        "unusedArguments",
        "consumerInfo",
        "apiKeyUid",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .unusedArguments) {
        self.unusedArguments = value
      }
      self.consumerInfo = try container.decodeIfPresent(
        CheckResponse.ConsumerInfo.self, forKey: .consumerInfo)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiKeyUid) {
        self.apiKeyUid = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.unusedArguments, forKey: .unusedArguments)
      try container.encodeIfPresent(self.consumerInfo, forKey: .consumerInfo)
      try container.encode(self.apiKeyUid, forKey: .apiKeyUid)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicecontrol.v1.CheckResponse.CheckInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// `ConsumerInfo` provides information about the consumer.
  public struct ConsumerInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Google cloud project number, e.g. 1234567890. A value of 0 indicates
    /// no project number is found.
    ///
    /// NOTE: This field is deprecated after we support flexible consumer
    /// id. New code should not depend on this field anymore.
    public var projectNumber: Swift.Int64 = Swift.Int64()

    /// The type of the consumer which should have been defined in
    /// [Google Resource Manager](https://cloud.google.com/resource-manager/).
    public var type: CheckResponse.ConsumerInfo.ConsumerType = CheckResponse.ConsumerInfo
      .ConsumerType()

    /// The consumer identity number, can be Google cloud project number, folder
    /// number or organization number e.g. 1234567890. A value of 0 indicates no
    /// consumer number is found.
    public var consumerNumber: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConsumerInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConsumerInfo().with { $0.projectNumber = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let projectNumber = CodingKeys(stringValue: "projectNumber")
      static let type = CodingKeys(stringValue: "type")
      static let consumerNumber = CodingKeys(stringValue: "consumerNumber")

      static let _knownKeys: Set<Swift.String> = [
        "projectNumber",
        "type",
        "consumerNumber",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .projectNumber) {
        self.projectNumber = value
      }
      if let value = try container.decodeIfPresent(
        CheckResponse.ConsumerInfo.ConsumerType.self, forKey: .type)
      {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .consumerNumber) {
        self.consumerNumber = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.projectNumber, forKey: .projectNumber)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.consumerNumber, forKey: .consumerNumber)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type of the consumer as defined in
    /// [Google Resource Manager](https://cloud.google.com/resource-manager/).
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ConsumerType: Codable, Equatable, Sendable {
      /// This is never used.
      case unspecified
      /// The consumer is a Google Cloud Project.
      case project
      /// The consumer is a Google Cloud Folder.
      case folder
      /// The consumer is a Google Cloud Organization.
      case organization
      /// Service-specific resource container which is defined by the service
      /// producer to offer their users the ability to manage service control
      /// functionalities at a finer level of granularity than the PROJECT.
      case serviceSpecific
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .project: return 1
        case .folder: return 2
        case .organization: return 3
        case .serviceSpecific: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CONSUMER_TYPE_UNSPECIFIED"
        case .project: return "PROJECT"
        case .folder: return "FOLDER"
        case .organization: return "ORGANIZATION"
        case .serviceSpecific: return "SERVICE_SPECIFIC"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConsumerType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CONSUMER_TYPE_UNSPECIFIED": self = .unspecified
        case "PROJECT": self = .project
        case "FOLDER": self = .folder
        case "ORGANIZATION": self = .organization
        case "SERVICE_SPECIFIC": self = .serviceSpecific
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConsumerType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .project
        case 2: self = .folder
        case 3: self = .organization
        case 4: self = .serviceSpecific
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("CONSUMER_TYPE_UNSPECIFIED")
        case .project: return try container.encode("PROJECT")
        case .folder: return try container.encode("FOLDER")
        case .organization: return try container.encode("ORGANIZATION")
        case .serviceSpecific: return try container.encode("SERVICE_SPECIFIC")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicecontrol.v1.CheckResponse.ConsumerInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.CheckResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
