// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Defines the errors to be returned in
/// [google.api.servicecontrol.v1.CheckResponse.check_errors][google.api.servicecontrol.v1.CheckResponse.check_errors].
///
/// [google.api.servicecontrol.v1.CheckResponse.check_errors]: <doc:CheckResponse/checkErrors>
public struct CheckError: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The error code.
  public var code: CheckError.Code = CheckError.Code()

  /// Subject to whom this error applies. See the specific code enum for more
  /// details on this field. For example:
  ///
  /// - "project:<project-id or project-number>"
  /// - "folder:<folder-id>"
  /// - "organization:<organization-id>"
  public var subject: Swift.String = Swift.String()

  /// Free-form text providing details on the error cause of the error.
  public var detail: Swift.String = Swift.String()

  /// Contains public information about the check error. If available,
  /// `status.code` will be non zero and client can propagate it out as public
  /// error.
  public var status: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CheckError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckError().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let code = CodingKeys(stringValue: "code")
    static let subject = CodingKeys(stringValue: "subject")
    static let detail = CodingKeys(stringValue: "detail")
    static let status = CodingKeys(stringValue: "status")

    static let _knownKeys: Set<Swift.String> = [
      "code",
      "subject",
      "detail",
      "status",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(CheckError.Code.self, forKey: .code) {
      self.code = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subject) {
      self.subject = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .detail) {
      self.detail = value
    }
    self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.code, forKey: .code)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.detail, forKey: .detail)
    try container.encodeIfPresent(self.status, forKey: .status)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Error codes for Check responses.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Code: Codable, Equatable, Hashable, Sendable {
    /// This is the default value if error code is not explicitly set.
    /// It should not be used directly.
    case errorCodeUnspecified
    /// The consumer's project id, network container, or resource container was
    /// not found. Same as
    /// [google.rpc.Code.NOT_FOUND][google.rpc.Code.NOT_FOUND].
    case notFound
    /// The consumer doesn't have access to the specified resource.
    /// Same as
    /// [google.rpc.Code.PERMISSION_DENIED][google.rpc.Code.PERMISSION_DENIED].
    case permissionDenied
    /// Quota check failed. Same as
    /// [google.rpc.Code.RESOURCE_EXHAUSTED][google.rpc.Code.RESOURCE_EXHAUSTED].
    case resourceExhausted
    /// The consumer hasn't activated the service.
    case serviceNotActivated
    /// The consumer's API key is invalid.
    case apiKeyInvalid
    /// The consumer cannot access the service because billing is disabled.
    case billingDisabled
    /// The consumer's project has been marked as deleted (soft deletion).
    case projectDeleted
    /// The IP address of the consumer is invalid for the specific consumer
    /// project.
    case ipAddressBlocked
    /// The referer address of the consumer request is invalid for the specific
    /// consumer project.
    case refererBlocked
    /// The client application of the consumer request is invalid for the
    /// specific consumer project.
    case clientAppBlocked
    /// The consumer's API Key has expired.
    case apiKeyExpired
    /// The consumer's API Key was not found in config record.
    case apiKeyNotFound
    /// The consumer's project number or id does not represent a valid project.
    case projectInvalid
    /// The API targeted by this request is invalid for the specified consumer
    /// project.
    case apiTargetBlocked
    /// The credential in the request can not be verified.
    case invalidCredential
    /// The input consumer info does not represent a valid consumer folder or
    /// organization.
    case consumerInvalid
    /// The backend server for looking up project id/number is unavailable.
    case namespaceLookupUnavailable
    /// The backend server for checking service status is unavailable.
    case serviceStatusUnavailable
    /// The backend server for checking billing status is unavailable.
    case billingStatusUnavailable
    /// Cloud Resource Manager backend server is unavailable.
    case cloudResourceManagerBackendUnavailable
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .errorCodeUnspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .errorCodeUnspecified: return 0
      case .notFound: return 5
      case .permissionDenied: return 7
      case .resourceExhausted: return 8
      case .serviceNotActivated: return 104
      case .apiKeyInvalid: return 105
      case .billingDisabled: return 107
      case .projectDeleted: return 108
      case .ipAddressBlocked: return 109
      case .refererBlocked: return 110
      case .clientAppBlocked: return 111
      case .apiKeyExpired: return 112
      case .apiKeyNotFound: return 113
      case .projectInvalid: return 114
      case .apiTargetBlocked: return 122
      case .invalidCredential: return 123
      case .consumerInvalid: return 125
      case .namespaceLookupUnavailable: return 300
      case .serviceStatusUnavailable: return 301
      case .billingStatusUnavailable: return 302
      case .cloudResourceManagerBackendUnavailable: return 305
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .errorCodeUnspecified: return "ERROR_CODE_UNSPECIFIED"
      case .notFound: return "NOT_FOUND"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .resourceExhausted: return "RESOURCE_EXHAUSTED"
      case .serviceNotActivated: return "SERVICE_NOT_ACTIVATED"
      case .apiKeyInvalid: return "API_KEY_INVALID"
      case .billingDisabled: return "BILLING_DISABLED"
      case .projectDeleted: return "PROJECT_DELETED"
      case .ipAddressBlocked: return "IP_ADDRESS_BLOCKED"
      case .refererBlocked: return "REFERER_BLOCKED"
      case .clientAppBlocked: return "CLIENT_APP_BLOCKED"
      case .apiKeyExpired: return "API_KEY_EXPIRED"
      case .apiKeyNotFound: return "API_KEY_NOT_FOUND"
      case .projectInvalid: return "PROJECT_INVALID"
      case .apiTargetBlocked: return "API_TARGET_BLOCKED"
      case .invalidCredential: return "INVALID_CREDENTIAL"
      case .consumerInvalid: return "CONSUMER_INVALID"
      case .namespaceLookupUnavailable: return "NAMESPACE_LOOKUP_UNAVAILABLE"
      case .serviceStatusUnavailable: return "SERVICE_STATUS_UNAVAILABLE"
      case .billingStatusUnavailable: return "BILLING_STATUS_UNAVAILABLE"
      case .cloudResourceManagerBackendUnavailable:
        return "CLOUD_RESOURCE_MANAGER_BACKEND_UNAVAILABLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ERROR_CODE_UNSPECIFIED": self = .errorCodeUnspecified
      case "NOT_FOUND": self = .notFound
      case "PERMISSION_DENIED": self = .permissionDenied
      case "RESOURCE_EXHAUSTED": self = .resourceExhausted
      case "SERVICE_NOT_ACTIVATED": self = .serviceNotActivated
      case "BILLING_DISABLED": self = .billingDisabled
      case "PROJECT_DELETED": self = .projectDeleted
      case "PROJECT_INVALID": self = .projectInvalid
      case "CONSUMER_INVALID": self = .consumerInvalid
      case "IP_ADDRESS_BLOCKED": self = .ipAddressBlocked
      case "REFERER_BLOCKED": self = .refererBlocked
      case "CLIENT_APP_BLOCKED": self = .clientAppBlocked
      case "API_TARGET_BLOCKED": self = .apiTargetBlocked
      case "API_KEY_INVALID": self = .apiKeyInvalid
      case "API_KEY_EXPIRED": self = .apiKeyExpired
      case "API_KEY_NOT_FOUND": self = .apiKeyNotFound
      case "INVALID_CREDENTIAL": self = .invalidCredential
      case "NAMESPACE_LOOKUP_UNAVAILABLE": self = .namespaceLookupUnavailable
      case "SERVICE_STATUS_UNAVAILABLE": self = .serviceStatusUnavailable
      case "BILLING_STATUS_UNAVAILABLE": self = .billingStatusUnavailable
      case "CLOUD_RESOURCE_MANAGER_BACKEND_UNAVAILABLE":
        self = .cloudResourceManagerBackendUnavailable
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .errorCodeUnspecified
      case 5: self = .notFound
      case 7: self = .permissionDenied
      case 8: self = .resourceExhausted
      case 104: self = .serviceNotActivated
      case 105: self = .apiKeyInvalid
      case 107: self = .billingDisabled
      case 108: self = .projectDeleted
      case 109: self = .ipAddressBlocked
      case 110: self = .refererBlocked
      case 111: self = .clientAppBlocked
      case 112: self = .apiKeyExpired
      case 113: self = .apiKeyNotFound
      case 114: self = .projectInvalid
      case 122: self = .apiTargetBlocked
      case 123: self = .invalidCredential
      case 125: self = .consumerInvalid
      case 300: self = .namespaceLookupUnavailable
      case 301: self = .serviceStatusUnavailable
      case 302: self = .billingStatusUnavailable
      case 305: self = .cloudResourceManagerBackendUnavailable
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .errorCodeUnspecified: return try container.encode("ERROR_CODE_UNSPECIFIED")
      case .notFound: return try container.encode("NOT_FOUND")
      case .permissionDenied: return try container.encode("PERMISSION_DENIED")
      case .resourceExhausted: return try container.encode("RESOURCE_EXHAUSTED")
      case .serviceNotActivated: return try container.encode("SERVICE_NOT_ACTIVATED")
      case .apiKeyInvalid: return try container.encode("API_KEY_INVALID")
      case .billingDisabled: return try container.encode("BILLING_DISABLED")
      case .projectDeleted: return try container.encode("PROJECT_DELETED")
      case .ipAddressBlocked: return try container.encode("IP_ADDRESS_BLOCKED")
      case .refererBlocked: return try container.encode("REFERER_BLOCKED")
      case .clientAppBlocked: return try container.encode("CLIENT_APP_BLOCKED")
      case .apiKeyExpired: return try container.encode("API_KEY_EXPIRED")
      case .apiKeyNotFound: return try container.encode("API_KEY_NOT_FOUND")
      case .projectInvalid: return try container.encode("PROJECT_INVALID")
      case .apiTargetBlocked: return try container.encode("API_TARGET_BLOCKED")
      case .invalidCredential: return try container.encode("INVALID_CREDENTIAL")
      case .consumerInvalid: return try container.encode("CONSUMER_INVALID")
      case .namespaceLookupUnavailable: return try container.encode("NAMESPACE_LOOKUP_UNAVAILABLE")
      case .serviceStatusUnavailable: return try container.encode("SERVICE_STATUS_UNAVAILABLE")
      case .billingStatusUnavailable: return try container.encode("BILLING_STATUS_UNAVAILABLE")
      case .cloudResourceManagerBackendUnavailable:
        return try container.encode("CLOUD_RESOURCE_MANAGER_BACKEND_UNAVAILABLE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.CheckError"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
