// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A common proto for logging HTTP requests. Only contains semantics
/// defined by the HTTP specification. Product-specific logging
/// information MUST be defined in a separate message.
public struct HttpRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The request method. Examples: `"GET"`, `"HEAD"`, `"PUT"`, `"POST"`.
  public var requestMethod: Swift.String = Swift.String()

  /// The scheme (http, https), the host name, the path, and the query
  /// portion of the URL that was requested.
  /// Example: `"http://example.com/some/info?color=red"`.
  public var requestUrl: Swift.String = Swift.String()

  /// The size of the HTTP request message in bytes, including the request
  /// headers and the request body.
  public var requestSize: Swift.Int64 = Swift.Int64()

  /// The response code indicating the status of the response.
  /// Examples: 200, 404.
  public var status: Swift.Int32 = Swift.Int32()

  /// The size of the HTTP response message sent back to the client, in bytes,
  /// including the response headers and the response body.
  public var responseSize: Swift.Int64 = Swift.Int64()

  /// The user agent sent by the client. Example:
  /// `"Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; Q312461; .NET
  /// CLR 1.0.3705)"`.
  public var userAgent: Swift.String = Swift.String()

  /// The IP address (IPv4 or IPv6) of the client that issued the HTTP
  /// request. Examples: `"192.168.1.1"`, `"FE80::0202:B3FF:FE1E:8329"`.
  public var remoteIp: Swift.String = Swift.String()

  /// The IP address (IPv4 or IPv6) of the origin server that the request was
  /// sent to.
  public var serverIp: Swift.String = Swift.String()

  /// The referer URL of the request, as defined in
  /// [HTTP/1.1 Header Field
  /// Definitions](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).
  public var referer: Swift.String = Swift.String()

  /// The request processing latency on the server, from the time the request was
  /// received until the response was sent.
  public var latency: GoogleWKT.WKTDuration? = nil

  /// Whether or not a cache lookup was attempted.
  public var cacheLookup: Swift.Bool = Swift.Bool()

  /// Whether or not an entity was served from cache
  /// (with or without validation).
  public var cacheHit: Swift.Bool = Swift.Bool()

  /// Whether or not the response was validated with the origin server before
  /// being served from cache. This field is only meaningful if `cache_hit` is
  /// True.
  public var cacheValidatedWithOriginServer: Swift.Bool = Swift.Bool()

  /// The number of HTTP response bytes inserted into cache. Set only when a
  /// cache fill was attempted.
  public var cacheFillBytes: Swift.Int64 = Swift.Int64()

  /// Protocol used for the request. Examples: "HTTP/1.1", "HTTP/2", "websocket"
  public var `protocol`: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HttpRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpRequest().with { $0.requestMethod = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let requestMethod = CodingKeys(stringValue: "requestMethod")
    static let requestUrl = CodingKeys(stringValue: "requestUrl")
    static let requestSize = CodingKeys(stringValue: "requestSize")
    static let status = CodingKeys(stringValue: "status")
    static let responseSize = CodingKeys(stringValue: "responseSize")
    static let userAgent = CodingKeys(stringValue: "userAgent")
    static let remoteIp = CodingKeys(stringValue: "remoteIp")
    static let serverIp = CodingKeys(stringValue: "serverIp")
    static let referer = CodingKeys(stringValue: "referer")
    static let latency = CodingKeys(stringValue: "latency")
    static let cacheLookup = CodingKeys(stringValue: "cacheLookup")
    static let cacheHit = CodingKeys(stringValue: "cacheHit")
    static let cacheValidatedWithOriginServer = CodingKeys(
      stringValue: "cacheValidatedWithOriginServer")
    static let cacheFillBytes = CodingKeys(stringValue: "cacheFillBytes")
    static let `protocol` = CodingKeys(stringValue: "protocol")

    static let _knownKeys: Set<Swift.String> = [
      "requestMethod",
      "requestUrl",
      "requestSize",
      "status",
      "responseSize",
      "userAgent",
      "remoteIp",
      "serverIp",
      "referer",
      "latency",
      "cacheLookup",
      "cacheHit",
      "cacheValidatedWithOriginServer",
      "cacheFillBytes",
      "protocol",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestMethod) {
      self.requestMethod = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestUrl) {
      self.requestUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .requestSize) {
      self.requestSize = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .status) {
      self.status = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .responseSize) {
      self.responseSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userAgent) {
      self.userAgent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remoteIp) {
      self.remoteIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serverIp) {
      self.serverIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .referer) {
      self.referer = value
    }
    self.latency = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .latency)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .cacheLookup) {
      self.cacheLookup = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .cacheHit) {
      self.cacheHit = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .cacheValidatedWithOriginServer)
    {
      self.cacheValidatedWithOriginServer = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .cacheFillBytes) {
      self.cacheFillBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .`protocol`) {
      self.`protocol` = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.requestMethod, forKey: .requestMethod)
    try container.encode(self.requestUrl, forKey: .requestUrl)
    try container.encode(self.requestSize, forKey: .requestSize)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.responseSize, forKey: .responseSize)
    try container.encode(self.userAgent, forKey: .userAgent)
    try container.encode(self.remoteIp, forKey: .remoteIp)
    try container.encode(self.serverIp, forKey: .serverIp)
    try container.encode(self.referer, forKey: .referer)
    try container.encodeIfPresent(self.latency, forKey: .latency)
    try container.encode(self.cacheLookup, forKey: .cacheLookup)
    try container.encode(self.cacheHit, forKey: .cacheHit)
    try container.encode(
      self.cacheValidatedWithOriginServer, forKey: .cacheValidatedWithOriginServer)
    try container.encode(self.cacheFillBytes, forKey: .cacheFillBytes)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.HttpRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
