// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleCloudLoggingType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An individual log entry.
public struct LogEntry: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The log to which this log entry belongs. Examples: `"syslog"`,
  /// `"book_log"`.
  public var name: Swift.String = Swift.String()

  /// The time the event described by the log entry occurred. If
  /// omitted, defaults to operation start time.
  public var timestamp: GoogleWKT.WKTTimestamp? = nil

  /// The severity of the log entry. The default value is
  /// `LogSeverity.DEFAULT`.
  public var severity: GoogleCloudLoggingType.LogSeverity = GoogleCloudLoggingType.LogSeverity()

  /// Optional. Information about the HTTP request associated with this
  /// log entry, if applicable.
  public var httpRequest: HttpRequest? = nil

  /// Optional. Resource name of the trace associated with the log entry, if any.
  /// If this field contains a relative resource name, you can assume the name is
  /// relative to `//tracing.googleapis.com`. Example:
  /// `projects/my-projectid/traces/06796866738c859f2f19b7cfb3214824`
  public var trace: Swift.String = Swift.String()

  /// A unique ID for the log entry used for deduplication. If omitted,
  /// the implementation will generate one based on operation_id.
  public var insertId: Swift.String = Swift.String()

  /// A set of user-defined (key, value) data that provides additional
  /// information about the log entry.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Information about an operation associated with the log entry, if
  /// applicable.
  public var operation: LogEntryOperation? = nil

  /// Optional. Source code location information associated with the log entry,
  /// if any.
  public var sourceLocation: LogEntrySourceLocation? = nil

  /// The log entry payload, which can be one of multiple types.
  public var payload: PayloadOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LogEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogEntry().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let timestamp = CodingKeys(stringValue: "timestamp")
    static let severity = CodingKeys(stringValue: "severity")
    static let httpRequest = CodingKeys(stringValue: "httpRequest")
    static let trace = CodingKeys(stringValue: "trace")
    static let insertId = CodingKeys(stringValue: "insertId")
    static let labels = CodingKeys(stringValue: "labels")
    static let protoPayload = CodingKeys(stringValue: "protoPayload")
    static let textPayload = CodingKeys(stringValue: "textPayload")
    static let structPayload = CodingKeys(stringValue: "structPayload")
    static let operation = CodingKeys(stringValue: "operation")
    static let sourceLocation = CodingKeys(stringValue: "sourceLocation")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "timestamp",
      "severity",
      "httpRequest",
      "trace",
      "insertId",
      "labels",
      "protoPayload",
      "textPayload",
      "structPayload",
      "operation",
      "sourceLocation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.timestamp = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .timestamp)
    if let value = try container.decodeIfPresent(
      GoogleCloudLoggingType.LogSeverity.self, forKey: .severity)
    {
      self.severity = value
    }
    self.httpRequest = try container.decodeIfPresent(HttpRequest.self, forKey: .httpRequest)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .trace) {
      self.trace = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .insertId) {
      self.insertId = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.operation = try container.decodeIfPresent(LogEntryOperation.self, forKey: .operation)
    self.sourceLocation = try container.decodeIfPresent(
      LogEntrySourceLocation.self, forKey: .sourceLocation)

    var payload: PayloadOneOf? = nil
    let payloadCheckAndSet = {
      if payload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'payload'"))
      }
      payload = $0
    }
    if let protoPayload = try container.decodeIfPresent(
      GoogleWKT.WKTAny?.self, forKey: .protoPayload)
    {
      try payloadCheckAndSet(.protoPayload(protoPayload))
    }
    if let textPayload = try container.decodeIfPresent(Swift.String.self, forKey: .textPayload) {
      try payloadCheckAndSet(.textPayload(textPayload))
    }
    if let structPayload = try container.decodeIfPresent(
      GoogleWKT.WKTStruct?.self, forKey: .structPayload)
    {
      try payloadCheckAndSet(.structPayload(structPayload))
    }
    self.payload = payload
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.timestamp, forKey: .timestamp)
    try container.encode(self.severity, forKey: .severity)
    try container.encodeIfPresent(self.httpRequest, forKey: .httpRequest)
    try container.encode(self.trace, forKey: .trace)
    try container.encode(self.insertId, forKey: .insertId)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.operation, forKey: .operation)
    try container.encodeIfPresent(self.sourceLocation, forKey: .sourceLocation)

    if let choice = self.payload {
      switch choice {
      case .protoPayload(let value):
        try container.encode(value, forKey: .protoPayload)
      case .textPayload(let value):
        try container.encode(value, forKey: .textPayload)
      case .structPayload(let value):
        try container.encode(value, forKey: .structPayload)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The log entry payload, which can be one of multiple types.
  public enum PayloadOneOf: Codable, Equatable, Sendable {
    /// The log entry payload, represented as a protocol buffer that is
    /// expressed as a JSON object. The only accepted type currently is
    /// [AuditLog][google.cloud.audit.AuditLog].
    indirect case protoPayload(GoogleWKT.WKTAny?)
    /// The log entry payload, represented as a Unicode string (UTF-8).
    case textPayload(Swift.String)
    /// The log entry payload, represented as a structure that
    /// is expressed as a JSON object.
    indirect case structPayload(GoogleWKT.WKTStruct?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.LogEntry"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
