// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents information regarding an operation.
public struct Operation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identity of the operation. This must be unique within the scope of the
  /// service that generated the operation. If the service calls
  /// Check() and Report() on the same operation, the two calls should carry
  /// the same id.
  ///
  /// UUID version 4 is recommended, though not required.
  /// In scenarios where an operation is computed from existing information
  /// and an idempotent id is desirable for deduplication purpose, UUID version 5
  /// is recommended. See RFC 4122 for details.
  public var operationId: Swift.String = Swift.String()

  /// Fully qualified name of the operation. Reserved for future use.
  public var operationName: Swift.String = Swift.String()

  /// Identity of the consumer who is using the service.
  /// This field should be filled in for the operations initiated by a
  /// consumer, but not for service-initiated operations that are
  /// not related to a specific consumer.
  ///
  ///
  /// - This can be in one of the following formats:
  ///     - project:PROJECT_ID,
  ///     - project`_`number:PROJECT_NUMBER,
  ///     - projects/PROJECT_ID or PROJECT_NUMBER,
  ///     - folders/FOLDER_NUMBER,
  ///     - organizations/ORGANIZATION_NUMBER,
  ///     - api`_`key:API_KEY.
  public var consumerId: Swift.String = Swift.String()

  /// Required. Start time of the operation.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// End time of the operation.
  /// Required when the operation is used in
  /// [ServiceController.Report][google.api.servicecontrol.v1.ServiceController.Report],
  /// but optional when the operation is used in
  /// [ServiceController.Check][google.api.servicecontrol.v1.ServiceController.Check].
  ///
  /// [google.api.servicecontrol.v1.ServiceController.Check]: <doc:ServiceControllerClient/check(request:options:)>
  /// [google.api.servicecontrol.v1.ServiceController.Report]: <doc:ServiceControllerClient/report(request:options:)>
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels describing the operation. Only the following labels are allowed:
  ///
  /// - Labels describing monitored resources as defined in
  ///   the service configuration.
  /// - Default labels of metric values. When specified, labels defined in the
  ///   metric value override these default.
  /// - The following labels defined by Google Cloud Platform:
  ///     - `cloud.googleapis.com/location` describing the location where the
  ///        operation happened,
  ///     - `servicecontrol.googleapis.com/user_agent` describing the user agent
  ///        of the API request,
  ///     - `servicecontrol.googleapis.com/service_agent` describing the service
  ///        used to handle the API request (e.g. ESP),
  ///     - `servicecontrol.googleapis.com/platform` describing the platform
  ///        where the API is served, such as App Engine, Compute Engine, or
  ///        Kubernetes Engine.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Represents information about this operation. Each MetricValueSet
  /// corresponds to a metric defined in the service configuration.
  /// The data type used in the MetricValueSet must agree with
  /// the data type specified in the metric definition.
  ///
  /// Within a single operation, it is not allowed to have more than one
  /// MetricValue instances that have the same metric names and identical
  /// label value combinations. If a request has such duplicated MetricValue
  /// instances, the entire request is rejected with
  /// an invalid argument error.
  public var metricValueSets: [MetricValueSet] = []

  /// Represents information to be logged.
  public var logEntries: [LogEntry] = []

  /// DO NOT USE. This is an experimental field.
  public var importance: Operation.Importance = Operation.Importance()

  /// Private Preview. This feature is only available for approved services.
  ///
  /// User defined labels for the resource that this operation is associated
  /// with.
  public var userLabels: [Swift.String: Swift.String] = [:]

  /// Unimplemented.
  public var extensions: [GoogleWKT.WKTAny] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Operation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Operation().with { $0.operationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let operationId = CodingKeys(stringValue: "operationId")
    static let operationName = CodingKeys(stringValue: "operationName")
    static let consumerId = CodingKeys(stringValue: "consumerId")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let metricValueSets = CodingKeys(stringValue: "metricValueSets")
    static let logEntries = CodingKeys(stringValue: "logEntries")
    static let importance = CodingKeys(stringValue: "importance")
    static let userLabels = CodingKeys(stringValue: "userLabels")
    static let extensions = CodingKeys(stringValue: "extensions")

    static let _knownKeys: Set<Swift.String> = [
      "operationId",
      "operationName",
      "consumerId",
      "startTime",
      "endTime",
      "labels",
      "metricValueSets",
      "logEntries",
      "importance",
      "userLabels",
      "extensions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationId) {
      self.operationId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationName) {
      self.operationName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .consumerId) {
      self.consumerId = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([MetricValueSet].self, forKey: .metricValueSets) {
      self.metricValueSets = value
    }
    if let value = try container.decodeIfPresent([LogEntry].self, forKey: .logEntries) {
      self.logEntries = value
    }
    if let value = try container.decodeIfPresent(Operation.Importance.self, forKey: .importance) {
      self.importance = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .userLabels)
    {
      self.userLabels = value
    }
    if let value = try container.decodeIfPresent([GoogleWKT.WKTAny].self, forKey: .extensions) {
      self.extensions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.operationId, forKey: .operationId)
    try container.encode(self.operationName, forKey: .operationName)
    try container.encode(self.consumerId, forKey: .consumerId)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.metricValueSets, forKey: .metricValueSets)
    try container.encode(self.logEntries, forKey: .logEntries)
    try container.encode(self.importance, forKey: .importance)
    try container.encode(self.userLabels, forKey: .userLabels)
    try container.encode(self.extensions, forKey: .extensions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Defines the importance of the data contained in the operation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Importance: Codable, Equatable, Sendable {
    /// Allows data caching, batching, and aggregation. It provides
    /// higher performance with higher data loss risk.
    case low
    /// Disables data aggregation to minimize data loss. It is for operations
    /// that contains significant monetary value or audit trail. This feature
    /// only applies to the client libraries.
    case high
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .low
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .low: return 0
      case .high: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .low: return "LOW"
      case .high: return "HIGH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Importance/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LOW": self = .low
      case "HIGH": self = .high
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Importance/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .low
      case 1: self = .high
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .low: return try container.encode("LOW")
      case .high: return try container.encode("HIGH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.Operation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
