// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents information regarding a quota operation.
public struct QuotaOperation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identity of the operation. For Allocation Quota, this is expected to be
  /// unique within the scope of the service that generated the operation, and
  /// guarantees idempotency in case of retries.
  ///
  /// In order to ensure best performance and latency in the Quota backends,
  /// operation_ids are optimally associated with time, so that related
  /// operations can be accessed fast in storage. For this reason, the
  /// recommended token for services that intend to operate at a high QPS is
  /// Unix time in nanos + UUID
  public var operationId: Swift.String = Swift.String()

  /// Fully qualified name of the API method for which this quota operation is
  /// requested. This name is used for matching quota rules or metric rules and
  /// billing status rules defined in service configuration.
  ///
  /// This field should not be set if any of the following is true:
  /// (1) the quota operation is performed on non-API resources.
  /// (2) quota_metrics is set because the caller is doing quota override.
  ///
  ///
  /// Example of an RPC method name:
  ///     google.example.library.v1.LibraryService.CreateShelf
  public var methodName: Swift.String = Swift.String()

  /// Identity of the consumer for whom this quota operation is being performed.
  ///
  /// This can be in one of the following formats:
  ///   project:<project_id>,
  ///   project_number:<project_number>,
  ///   api_key:<api_key>.
  public var consumerId: Swift.String = Swift.String()

  /// Labels describing the operation.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Represents information about this operation. Each MetricValueSet
  /// corresponds to a metric defined in the service configuration.
  /// The data type used in the MetricValueSet must agree with
  /// the data type specified in the metric definition.
  ///
  /// Within a single operation, it is not allowed to have more than one
  /// MetricValue instances that have the same metric names and identical
  /// label value combinations. If a request has such duplicated MetricValue
  /// instances, the entire request is rejected with
  /// an invalid argument error.
  ///
  /// This field is mutually exclusive with method_name.
  public var quotaMetrics: [MetricValueSet] = []

  /// Quota mode for this operation.
  public var quotaMode: QuotaOperation.QuotaMode = QuotaOperation.QuotaMode()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QuotaOperation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaOperation().with { $0.operationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let operationId = CodingKeys(stringValue: "operationId")
    static let methodName = CodingKeys(stringValue: "methodName")
    static let consumerId = CodingKeys(stringValue: "consumerId")
    static let labels = CodingKeys(stringValue: "labels")
    static let quotaMetrics = CodingKeys(stringValue: "quotaMetrics")
    static let quotaMode = CodingKeys(stringValue: "quotaMode")

    static let _knownKeys: Set<Swift.String> = [
      "operationId",
      "methodName",
      "consumerId",
      "labels",
      "quotaMetrics",
      "quotaMode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationId) {
      self.operationId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .methodName) {
      self.methodName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .consumerId) {
      self.consumerId = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([MetricValueSet].self, forKey: .quotaMetrics) {
      self.quotaMetrics = value
    }
    if let value = try container.decodeIfPresent(QuotaOperation.QuotaMode.self, forKey: .quotaMode)
    {
      self.quotaMode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.operationId, forKey: .operationId)
    try container.encode(self.methodName, forKey: .methodName)
    try container.encode(self.consumerId, forKey: .consumerId)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.quotaMetrics, forKey: .quotaMetrics)
    try container.encode(self.quotaMode, forKey: .quotaMode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Supported quota modes.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum QuotaMode: Codable, Equatable, Hashable, Sendable {
    /// Guard against implicit default. Must not be used.
    case unspecified
    /// For AllocateQuota request, allocates quota for the amount specified in
    /// the service configuration or specified using the quota metrics. If the
    /// amount is higher than the available quota, allocation error will be
    /// returned and no quota will be allocated.
    /// If multiple quotas are part of the request, and one fails, none of the
    /// quotas are allocated or released.
    case normal
    /// The operation allocates quota for the amount specified in the service
    /// configuration or specified using the quota metrics. If the amount is
    /// higher than the available quota, request does not fail but all available
    /// quota will be allocated.
    /// For rate quota, BEST_EFFORT will continue to deduct from other groups
    /// even if one does not have enough quota. For allocation, it will find the
    /// minimum available amount across all groups and deduct that amount from
    /// all the affected groups.
    case bestEffort
    /// For AllocateQuota request, only checks if there is enough quota
    /// available and does not change the available quota. No lock is placed on
    /// the available quota either.
    case checkOnly
    /// Unimplemented. When used in AllocateQuotaRequest, this returns the
    /// effective quota limit(s) in the response, and no quota check will be
    /// performed. Not supported for other requests, and even for
    /// AllocateQuotaRequest, this is currently supported only for allowlisted
    /// services.
    case queryOnly
    /// The operation allocates quota for the amount specified in the service
    /// configuration or specified using the quota metrics. If the requested
    /// amount is higher than the available quota, request does not fail and
    /// remaining quota would become negative (going over the limit).
    /// Not supported for Rate Quota.
    case adjustOnly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .normal: return 1
      case .bestEffort: return 2
      case .checkOnly: return 3
      case .queryOnly: return 4
      case .adjustOnly: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .normal: return "NORMAL"
      case .bestEffort: return "BEST_EFFORT"
      case .checkOnly: return "CHECK_ONLY"
      case .queryOnly: return "QUERY_ONLY"
      case .adjustOnly: return "ADJUST_ONLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:QuotaMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "NORMAL": self = .normal
      case "BEST_EFFORT": self = .bestEffort
      case "CHECK_ONLY": self = .checkOnly
      case "QUERY_ONLY": self = .queryOnly
      case "ADJUST_ONLY": self = .adjustOnly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:QuotaMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .normal
      case 2: self = .bestEffort
      case 3: self = .checkOnly
      case 4: self = .queryOnly
      case 5: self = .adjustOnly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("UNSPECIFIED")
      case .normal: return try container.encode("NORMAL")
      case .bestEffort: return try container.encode("BEST_EFFORT")
      case .checkOnly: return try container.encode("CHECK_ONLY")
      case .queryOnly: return try container.encode("QUERY_ONLY")
      case .adjustOnly: return try container.encode("ADJUST_ONLY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.QuotaOperation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
