// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents error information for
/// [QuotaOperation][google.api.servicecontrol.v1.QuotaOperation].
///
/// [google.api.servicecontrol.v1.QuotaOperation]: <doc:QuotaOperation>
public struct QuotaError: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Error code.
  public var code: QuotaError.Code = QuotaError.Code()

  /// Subject to whom this error applies. See the specific enum for more details
  /// on this field. For example, "clientip:<ip address of client>" or
  /// "project:<Google developer project id>".
  public var subject: Swift.String = Swift.String()

  /// Free-form text that provides details on the cause of the error.
  public var description: Swift.String = Swift.String()

  /// Contains additional information about the quota error.
  /// If available, `status.code` will be non zero.
  public var status: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QuotaError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaError().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let code = CodingKeys(stringValue: "code")
    static let subject = CodingKeys(stringValue: "subject")
    static let description = CodingKeys(stringValue: "description")
    static let status = CodingKeys(stringValue: "status")

    static let _knownKeys: Set<Swift.String> = [
      "code",
      "subject",
      "description",
      "status",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(QuotaError.Code.self, forKey: .code) {
      self.code = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subject) {
      self.subject = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.code, forKey: .code)
    try container.encode(self.subject, forKey: .subject)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.status, forKey: .status)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Error codes related to project config validations are deprecated since the
  /// quota controller methods do not perform these validations. Instead services
  /// have to call the Check method, without quota_properties field, to perform
  /// these validations before calling the quota controller methods. These
  /// methods check only for project deletion to be wipe out compliant.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Code: Codable, Equatable, Sendable {
    /// This is never used.
    case unspecified
    /// Quota allocation failed.
    /// Same as
    /// [google.rpc.Code.RESOURCE_EXHAUSTED][google.rpc.Code.RESOURCE_EXHAUSTED].
    case resourceExhausted
    /// Specified API key is invalid.
    case apiKeyInvalid
    /// Consumer cannot access the service because the service requires active
    /// billing.
    case billingNotActive
    /// Consumer's project has been marked as deleted (soft deletion).
    case projectDeleted
    /// Specified API Key has expired.
    case apiKeyExpired
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resourceExhausted: return 8
      case .apiKeyInvalid: return 105
      case .billingNotActive: return 107
      case .projectDeleted: return 108
      case .apiKeyExpired: return 112
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .resourceExhausted: return "RESOURCE_EXHAUSTED"
      case .apiKeyInvalid: return "API_KEY_INVALID"
      case .billingNotActive: return "BILLING_NOT_ACTIVE"
      case .projectDeleted: return "PROJECT_DELETED"
      case .apiKeyExpired: return "API_KEY_EXPIRED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "RESOURCE_EXHAUSTED": self = .resourceExhausted
      case "BILLING_NOT_ACTIVE": self = .billingNotActive
      case "PROJECT_DELETED": self = .projectDeleted
      case "API_KEY_INVALID": self = .apiKeyInvalid
      case "API_KEY_EXPIRED": self = .apiKeyExpired
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 8: self = .resourceExhausted
      case 105: self = .apiKeyInvalid
      case 107: self = .billingNotActive
      case 108: self = .projectDeleted
      case 112: self = .apiKeyExpired
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("UNSPECIFIED")
      case .resourceExhausted: return try container.encode("RESOURCE_EXHAUSTED")
      case .apiKeyInvalid: return try container.encode("API_KEY_INVALID")
      case .billingNotActive: return try container.encode("BILLING_NOT_ACTIVE")
      case .projectDeleted: return try container.encode("PROJECT_DELETED")
      case .apiKeyExpired: return try container.encode("API_KEY_EXPIRED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.QuotaError"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
