// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for the Report method.
public struct ReportResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Partial failures, one for each `Operation` in the request that failed
  /// processing. There are three possible combinations of the RPC status:
  ///
  /// 1. The combination of a successful RPC status and an empty `report_errors`
  ///    list indicates a complete success where all `Operations` in the
  ///    request are processed successfully.
  /// 2. The combination of a successful RPC status and a non-empty
  ///    `report_errors` list indicates a partial success where some
  ///    `Operations` in the request succeeded. Each
  ///    `Operation` that failed processing has a corresponding item
  ///    in this list.
  /// 3. A failed RPC status indicates a general non-deterministic failure.
  ///    When this happens, it's impossible to know which of the
  ///    'Operations' in the request succeeded or failed.
  public var reportErrors: [ReportResponse.ReportError] = []

  /// The actual config id used to process the request.
  public var serviceConfigId: Swift.String = Swift.String()

  /// The current service rollout id used to process the request.
  public var serviceRolloutId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReportResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReportResponse().with { $0.reportErrors = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let reportErrors = CodingKeys(stringValue: "reportErrors")
    static let serviceConfigId = CodingKeys(stringValue: "serviceConfigId")
    static let serviceRolloutId = CodingKeys(stringValue: "serviceRolloutId")

    static let _knownKeys: Set<Swift.String> = [
      "reportErrors",
      "serviceConfigId",
      "serviceRolloutId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ReportResponse.ReportError].self, forKey: .reportErrors)
    {
      self.reportErrors = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceConfigId) {
      self.serviceConfigId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceRolloutId) {
      self.serviceRolloutId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.reportErrors, forKey: .reportErrors)
    try container.encode(self.serviceConfigId, forKey: .serviceConfigId)
    try container.encode(self.serviceRolloutId, forKey: .serviceRolloutId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents the processing error of one
  /// [Operation][google.api.servicecontrol.v1.Operation] in the request.
  ///
  /// [google.api.servicecontrol.v1.Operation]: <doc:Operation>
  public struct ReportError: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The
    /// [Operation.operation_id][google.api.servicecontrol.v1.Operation.operation_id]
    /// value from the request.
    ///
    /// [google.api.servicecontrol.v1.Operation.operation_id]: <doc:Operation/operationId>
    public var operationId: Swift.String = Swift.String()

    /// Details of the error when processing the
    /// [Operation][google.api.servicecontrol.v1.Operation].
    ///
    /// [google.api.servicecontrol.v1.Operation]: <doc:Operation>
    public var status: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ReportError`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReportError().with { $0.operationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let operationId = CodingKeys(stringValue: "operationId")
      static let status = CodingKeys(stringValue: "status")

      static let _knownKeys: Set<Swift.String> = [
        "operationId",
        "status",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationId) {
        self.operationId = value
      }
      self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.operationId, forKey: .operationId)
      try container.encodeIfPresent(self.status, forKey: .status)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicecontrol.v1.ReportResponse.ReportError"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.ReportResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
