// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// [Google Service Control
/// API](https://cloud.google.com/service-control/overview)
///
/// Lets clients check and report operations against a [managed
/// service](https://cloud.google.com/service-management/reference/rpc/google.api/servicemanagement.v1#google.api.servicemanagement.v1.ManagedService).
///
/// @Snippet(path: "ServiceControllerQuickstart")
public final class ServiceControllerClient: Clients.ServiceControllerProtocol, Sendable {
  let inner: any Clients.ServiceControllerStub

  /// Creates a new `ServiceControllerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ServiceControllerStub = try Clients.ServiceControllerTransport(options)
    inner = Clients.ServiceControllerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ServiceControllerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Checks whether an operation on a service should be allowed to proceed
  /// based on the configuration of the service and related policies. It must be
  /// called before the operation is executed.
  ///
  /// If feasible, the client should cache the check results and reuse them for
  /// 60 seconds. In case of any server errors, the client should rely on the
  /// cached results for much longer time to avoid outage.
  /// WARNING: There is general 60s delay for the configuration and policy
  /// propagation, therefore callers MUST NOT depend on the `Check` method having
  /// the latest policy information.
  ///
  /// NOTE: the [CheckRequest][google.api.servicecontrol.v1.CheckRequest] has the
  /// size limit (wire-format byte size) of 1MB.
  ///
  /// This method requires the `servicemanagement.services.check` permission
  /// on the specified service. For more information, see
  /// [Cloud IAM](https://cloud.google.com/iam).
  ///
  /// [google.api.servicecontrol.v1.CheckRequest]: <doc:CheckRequest>
  ///
  /// @Snippet(path: "ServiceController_Check")
  public func check(
    request: CheckRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV1.CheckResponse {
    try await self.inner.check(request: request, options: options)
  }

  /// Reports operation results to Google Service Control, such as logs and
  /// metrics. It should be called after an operation is completed.
  ///
  /// If feasible, the client should aggregate reporting data for up to 5
  /// seconds to reduce API traffic. Limiting aggregation to 5 seconds is to
  /// reduce data loss during client crashes. Clients should carefully choose
  /// the aggregation time window to avoid data loss risk more than 0.01%
  /// for business and compliance reasons.
  ///
  /// NOTE: the [ReportRequest][google.api.servicecontrol.v1.ReportRequest] has
  /// the size limit (wire-format byte size) of 1MB.
  ///
  /// This method requires the `servicemanagement.services.report` permission
  /// on the specified service. For more information, see
  /// [Google Cloud IAM](https://cloud.google.com/iam).
  ///
  /// [google.api.servicecontrol.v1.ReportRequest]: <doc:ReportRequest>
  ///
  /// @Snippet(path: "ServiceController_Report")
  public func report(
    request: ReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV1.ReportResponse {
    try await self.inner.report(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ServiceControllerClient`.
  ///
  /// To mock `ServiceControllerClient` change your functions to receive
  /// `some ServiceControllerProtocol` or `any ServiceControllerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ServiceControllerProtocol: Sendable {
    /// See `ServiceControllerClient.check`.
    func check(
      request: CheckRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceControlV1.CheckResponse

    /// See `ServiceControllerClient.report`.
    func report(
      request: ReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceControlV1.ReportResponse
  }
}

// Default implementations
extension Clients.ServiceControllerProtocol {
  public func check(request: CheckRequest) async throws -> GoogleApiServiceControlV1.CheckResponse {
    try await self.check(request: request, options: .init())
  }

  public func check(
    request: CheckRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV1.CheckResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func report(request: ReportRequest) async throws
    -> GoogleApiServiceControlV1.ReportResponse
  {
    try await self.report(request: request, options: .init())
  }

  public func report(
    request: ReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV1.ReportResponse {
    throw GoogleGax.RequestError.unimplemented
  }
}
